version: "3.9"

services:
  db:
    image: postgres:15
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata_local:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      PLAYWRIGHT_BROWSERS_PATH: /app/.pw-browsers
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      DJANGO_RUNSERVER: "1"   # En local usamos runserver con autoreload
      DEBUG: "1"
      POSTGRES_HOST: db # Superusuario de la base de datos: admin, pass duocuc1234
      POSTGRES_PORT: 5432 
      BNE_TOKEN_URL: https://test.api.bne.cl/token
      BNE_CLIENT_ID: e9b75m_XYbA5n0Dz33M_rbChsRMa
      BNE_CLIENT_SECRET: bbctfOeNTfCyfhNa_xOl5kafYvMa
    shm_size: '2gb'      # Chromium necesita algo de /dev/shm
    cap_add:
      - SYS_ADMIN 
    volumes:
      - .:/app
      - static_local:/app/staticfiles
      - media_local:/app/media
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8090:8000"  # accedes en http://localhost:8090

  # Nginx es opcional en local. Si quieres parity con prod, actívalo.
  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_local:/static
      - media_local:/media
    ports:
      - "8080:80"   # accedes también por http://localhost:8080 (vía Nginx)
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1

volumes:
  pgdata_local:
  static_local:
  media_local:
